parameters:
  weight_scale: 1e-6
  lr: 5e-3

data:
  root: data/samples/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.05
