parameters:
  weight_scale: 1e-6
  lr: 1e-2

data:
  root: data/samples/

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: ./bkse/options/generate_blur/default.yml

  noise: 
    name: gaussian
    sigma: 0.05
