parameters:
  weight_scale: 1e-6
  lr: 5e-3

data:
  root: data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256

  noise:
    name: gaussian
    sigma: 0.05
